// Generated file, do not modify manually!

// Code generated by client-gen. DO NOT EDIT.

package client

import (
	glog "github.com/golang/glog"
	brokernetesv1 "github.com/nilebox/brokernetes/pkg/controller/client/typed/brokernetes/v1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	BrokernetesV1() brokernetesv1.BrokernetesV1Interface
	// Deprecated: please explicitly pick a version if possible.
	Brokernetes() brokernetesv1.BrokernetesV1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	brokernetesV1 *brokernetesv1.BrokernetesV1Client
}

// BrokernetesV1 retrieves the BrokernetesV1Client
func (c *Clientset) BrokernetesV1() brokernetesv1.BrokernetesV1Interface {
	return c.brokernetesV1
}

// Deprecated: Brokernetes retrieves the default version of BrokernetesClient.
// Please explicitly pick a version.
func (c *Clientset) Brokernetes() brokernetesv1.BrokernetesV1Interface {
	return c.brokernetesV1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.brokernetesV1, err = brokernetesv1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		glog.Errorf("failed to create the DiscoveryClient: %v", err)
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.brokernetesV1 = brokernetesv1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.brokernetesV1 = brokernetesv1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
