// Generated file, do not modify manually!

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/nilebox/brokernetes/pkg/apis/brokernetes/v1"
	"github.com/nilebox/brokernetes/pkg/controller/client/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type BrokernetesV1Interface interface {
	RESTClient() rest.Interface
	InstancesGetter
}

// BrokernetesV1Client is used to interact with features provided by the brokernetes group.
type BrokernetesV1Client struct {
	restClient rest.Interface
}

func (c *BrokernetesV1Client) Instances(namespace string) InstanceInterface {
	return newInstances(c, namespace)
}

// NewForConfig creates a new BrokernetesV1Client for the given config.
func NewForConfig(c *rest.Config) (*BrokernetesV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &BrokernetesV1Client{client}, nil
}

// NewForConfigOrDie creates a new BrokernetesV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *BrokernetesV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new BrokernetesV1Client for the given RESTClient.
func New(c rest.Interface) *BrokernetesV1Client {
	return &BrokernetesV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *BrokernetesV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
